name: aiops-fault-diagnosis-agent
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - torch==2.14.1+cu130
      - -e .[dev]
